name: Development workflow

on:
  push:
    branches:
      - main

# Here the environment variable is declared in workflow level
env:
  # Replace with your Orchestrator Values
  PROJECT_NAME: TestProject
  PROJECT_FOLDER: Shared
  ORCH_URL: https://staging.uipath.com
  ORCH_TENANT: DefaultTenant
  ORCH_CLIENT_ID: 85ebb9c0-702b-476e-9d67-68bc983c630e
  ORCH_USER_KEY: QouB^DSIGnDwBAgg4Qn*IC3e%WRI$Ay_ky5*ZEKSL#rqB0AzE0ch5!G0!?^@_u#t
  ORCH_ACC_NAME: uipatbhekmar

jobs:
  pack:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output folder
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path "${{ github.workspace }}\output"

      - name: Pack UiPath Project
        shell: powershell
        run: |
          $projectPath = "${{ github.workspace }}\project.json"
          $outputPath = "${{ github.workspace }}\output"
          $cliPath = "${{ github.workspace }}\cli\tools\uipcli.exe"

          & "$cliPath" package pack `
            "$projectPath" `
            -o "$outputPath" `
            --autoVersion

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uipath-package
          path: output/*.nupkg

  publish-uipath-nuget-package:
    needs: pack
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download UiPath Artifact
        uses: actions/download-artifact@v4
        with:
          name: uipath-package
          path: package   # download into /package folder

      - name: Deploy to UiPath Orchestrator
        shell: powershell
        run: |
          $cliPath = "${{ github.workspace }}\cli\tools\uipcli.exe"
          $packagePath = "${{ github.workspace }}\package"

          & "$cliPath" package deploy `
            "$packagePath" `
            "${{ env.ORCH_URL }}" `
            "${{ env.ORCH_TENANT }}" `
            -A "${{ env.ORCH_ACC_NAME }}" `
            -I "${{ env.ORCH_CLIENT_ID }}" `
            -S 'QouB^DSIGnDwBAgg4Qn*IC3e%WRI$Ay_ky5*ZEKSL#rqB0AzE0ch5!G0!?^@_u#t' `
            --applicationScope "OR.Folders OR.BackgroundTasks OR.TestSets OR.TestSetExecutions OR.TestSetSchedules OR.Settings.Read OR.Robots.Read OR.Machines.Read OR.Execution OR.Assets OR.Users.Read OR.Jobs OR.Monitoring" `
            --organizationUnit "${{ env.PROJECT_FOLDER }}" `
            --traceLevel Information `
            --entryPointsPath "Main.xaml"

  
