name: Development workflow

on:
  push:
    branches:
      - main

# Here the environment variable is declared in workflow level
env:
  # Replace with your Orchestrator Values
  PROJECT_NAME: PatientChartDownload_AdvancedMD
  PROJECT_FOLDER: Shared
  ORCH_URL: https://staging.uipath.com
  ORCH_TENANT: DefaultTenant
  ORCH_CLIENT_ID: ADLqfy4M6cRUaEL6XOxiKpMqyPvjTuUi
  ORCH_USER_KEY: WbF2D1YK4j4jLBJAhAYD3lKhJ3YqEVdHMRKzlXR3o2t5M
  ORCH_ACC_NAME: uipatbhekmar

jobs:
  pack:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output folder
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path "${{ github.workspace }}\output"

      - name: Pack UiPath Project
        shell: powershell
        run: |
          $projectPath = "${{ github.workspace }}\project.json"
          $outputPath = "${{ github.workspace }}\output"
          $cliPath = "${{ github.workspace }}\cli\tools\uipcli.exe"

          & "$cliPath" package pack `
            "$projectPath" `
            -o "$outputPath" `
            --autoVersion

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uipath-package
          path: output/*.nupkg

  publish-uipath-nuget-package:
    needs: pack
    runs-on: windows-latest
    steps:
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v4
        with:
          name: uipath-package

      - name: Publish Nuget Package to DEV
        shell: pwsh
        run: |
          ${{ github.workspace }}\scripts\UiPathDeploy.ps1 `
          ${{ github.workspace }}\package `
          ${{ env.ORCH_URL }} `
          ${{ env.ORCH_TENANT }} `
          -UserKey ${{ env.ORCH_USER_KEY }} `
          -account_name ${{ env.ORCH_ACC_NAME }}

  
