name: Development workflow

on:
  push:
    branches:
      - main

# Here the environment variable is declared in workflow level
env:
  # Replace with your Orchestrator Values
  PROJECT_NAME: PatientChartDownload_AdvancedMD
  PROJECT_FOLDER: Shared
  ORCH_URL: https://staging.uipath.com
  ORCH_TENANT: DefaultTenant
  ORCH_CLIENT_ID: ADLqfy4M6cRUaEL6XOxiKpMqyPvjTuUi
  ORCH_USER_KEY: WbF2D1YK4j4jLBJAhAYD3lKhJ3YqEVdHMRKzlXR3o2t5M
  ORCH_ACC_NAME: uipatbhekmar

jobs:
  print-details:
    runs-on: windows-latest
    steps:
      - name: echo-default-env-variables
        shell: pwsh
        run: |
          Write-Output "Home: $env:USERPROFILE"
          Write-Output "GITHUB_WORKFLOW: $env:GITHUB_WORKFLOW"
          Write-Output "GITHUB_ACTIONS: $env:GITHUB_ACTIONS"
          Write-Output "GITHUB_ACTOR: $env:GITHUB_ACTOR"
          Write-Output "GITHUB_REPOSITORY: $env:GITHUB_REPOSITORY"
          Write-Output "GITHUB_EVENT_NAME: $env:GITHUB_EVENT_NAME"
          Write-Output "GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
          Write-Output "GITHUB_SHA: $env:GITHUB_SHA"
          Write-Output "GITHUB_REF: $env:GITHUB_REF"

  cleaner:
    runs-on: windows-latest
    steps:
      - name: Runner workspace path
        shell: pwsh
        run: |
          Write-Output "Cleaning up previous run"
          if (Test-Path "${{ github.workspace }}") { Remove-Item -LiteralPath "${{ github.workspace }}" -Recurse -Force -ErrorAction SilentlyContinue }

  build-uipath-nuget-package:
    needs: cleaner
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # âœ… Install required .NET 6 SDK
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Verify .NET installation
        run: dotnet --info

      - name: Build Nuget Package
        shell: pwsh
        run: |
          ${{ github.workspace }}\scripts\UiPathPack.ps1 `
          ${{ github.workspace }}\project.json `
          -destination_folder ${{ github.workspace }}\package `
          -CliPath ${{ github.workspace }}\cli\tools\uipcli.exe

      - name: Upload UiPath Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            package/*.*
            scripts/*.ps1

  publish-uipath-nuget-package:
    needs: build-uipath-nuget-package
    runs-on: windows-latest
    steps:
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts

      - name: Publish Nuget Package to DEV
        shell: pwsh
        run: |
          ${{ github.workspace }}\scripts\UiPathDeploy.ps1 `
          ${{ github.workspace }}\package `
          ${{ env.ORCH_URL }} `
          ${{ env.ORCH_TENANT }} `
          -UserKey ${{ env.ORCH_USER_KEY }} `
          -account_name ${{ env.ORCH_ACC_NAME }}

  
